name: Update report

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate report.json
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: python collect_data.py

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push if changed
        run: |
          git add docs/report.json
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update report.json [auto]"
            git push
          fi
